{
  "hash": "5ae8b41d299aa3f2ca9fda067a2bf5c2",
  "result": {
    "engine": "knitr",
    "markdown": "# Cryptographic Primitives {#sec-crypto}\n\n::: {.bookepigraph}\n\n\n\n\n\n```{=latex}\n\\begin{flushright}\\small\n```\n\n\n\n\n\n*We stand today on the brink of a revolution in\ncryptography.*\n\n[Diffie and Hellman]{.smallcaps}, *New Directions in\nCryptography* (1976)\n\n\n\n\n\n```{=latex}\n\\end{flushright}\n```\n\n\n\n\n\n:::\n\n## Learning objectives\n\nBy the end of this chapter the reader should be\nable to:\n\n- State the random-oracle idealisation of a\n  cryptographic hash and name the five\n  properties (determinism, preimage resistance,\n  collision resistance, avalanche, uniformity)\n  it is meant to capture.\n- Derive the birthday bound and explain why\n  collision resistance ($\\sim 2^{n/2}$) is the\n  harder property to guarantee than preimage\n  resistance ($\\sim 2^{n}$).\n- Verify the avalanche and uniformity properties\n  empirically in R and read the statistical\n  tests as evidence for the random-oracle model.\n- Construct a Merkle tree, produce a logarithmic\n  inclusion proof, and verify membership without\n  the underlying data.\n- Explain the elliptic-curve group law, the role\n  of discrete-log hardness in digital signatures,\n  and what signature aggregation buys.\n- Judge when a published Merkle root is the right\n  tool for dataset integrity and when it is not.\n\n## Orientation\n\nWe begin with a problem from the conduct of a\nclinical trial. A multi-institution trial, run\nacross several hospitals with no single trusted\ncustodian of the data, reaches its lock date. At\nthat moment the sites wish to commit irrevocably\nto the dataset as it stands on that date: the\nenrolments, the randomisation assignments, and the\noutcome events recorded to date. Analysis and\nunblinding will follow, and a regulator may, months\nor years later, wish to verify that the dataset\nexamined at audit is exactly the one that was\nlocked, that no record was quietly altered, added,\nor removed in the interval. We shall refer to this\nshared, append-only record, maintained across\ninstitutions with no single custodian, as the trial\nledger, and it recurs throughout the book. The\nquestion before us is narrow and answerable: by what\nmechanism can the sites commit to the locked data in\na way that a later auditor can check?\n\nThe machinery that answers it is the subject of this\nchapter. The hash of the locked dataset is a short\nfingerprint that changes if any byte of the data\nchanges. A Merkle tree built over the per-record\nhashes lets an auditor verify a single record\nwithout possessing the whole database. Digital\nsignatures attach to each entry the identity of the\ncoordinator who made it, so that attribution of an\neCRF record (an electronic case report form, the\nrecord of one subject's data in the trial) becomes\nitself cryptographically checkable. Digital cash and cryptocurrency are where\nthese primitives were sharpened, and we shall keep\nthat history in view; but for our purposes they are\nthe historical setting and not the frame.\n\nThe primitives are usually taught as engineering\nartefacts, a matter of invoking a library and\nobtaining a guarantee. For a reader with graduate\nprobability and algebra they are better understood\nas mathematical objects with statistical behaviour\nthat can be measured. A\ncryptographic hash is, to the precision that matters\nhere, a random function. An elliptic curve over a\nfinite field is a finite abelian group in which one\ndirection of arithmetic is easy and its inverse is\nbelieved hard. Every security property we shall\ninvoke is a statement about the difficulty of a\nsearch, and the difficulty of a search is a\nprobability calculation.\n\nThat reframing pays immediately. The reason six\nconfirmations suffice in @sec-pow, the reason a\nlight client can trust a block header without the\nblock body, and the reason a public key does not\nleak its private key, are all consequences of two\nnumbers: the expected work to find a preimage and\nthe expected work to find a collision. We shall\nderive both, and then confirm the underlying\nrandom-oracle assumption by hashing tens of\nthousands of strings in R and subjecting the output\nto the same goodness-of-fit tests we would apply to\nany claimed random-number generator.\n\nHere the empirical stance deserves emphasis, and it\nis worth stating in a form familiar to any reader\nwho has validated an assay before trusting its\nreadings. We do not take the random-oracle model on\nfaith. Cryptographers prove theorems about these\nobjects under stated hardness assumptions; a\nstatistician can, in addition, treat the deployed\nhash as an unknown distribution and test its\nobservable consequences, exactly as one runs known\nsamples through a new assay to confirm that it\nbehaves as specified before admitting its readings\ninto evidence. The tests in this chapter do not\nprove SHA-256 secure, and we shall be careful to say\nwhat they do and do not establish. They verify that\nits output is consistent with the random-oracle\nmodel, which is the assumption every later\nprobability calculation silently uses.\n\n::: {.callout-note}\n## The vocabulary of this chapter\n\nThe argument turns on a handful of terms that a\nfirst-year public-health reader is unlikely to\nhave met. We define them here and use them\nconsistently thereafter.\n\n- **Random oracle.** An idealised hash function\n  imagined as assigning each distinct input an\n  independent, uniformly random output. It is the\n  working model under which every probability in\n  the chapter is computed.\n- **Preimage resistance.** The property that,\n  given a digest, no feasible search recovers an\n  input producing it; the expected work is about\n  $2^{n}$ for an $n$-bit digest.\n- **Collision resistance.** The property that no\n  feasible search finds two distinct inputs\n  sharing a digest. The birthday bound makes this\n  cost about $2^{n/2}$, far less than preimage\n  resistance.\n- **Birthday bound.** The result that a collision\n  among random draws from a space of size $N$\n  becomes likely after only about $\\sqrt{N}$\n  draws rather than $N$; it is the familiar\n  birthday problem applied to digests.\n- **Merkle tree.** A hash-based summary that\n  commits to many records at once. Its top hash,\n  the *Merkle root*, is a single fingerprint of\n  the whole set, and an *inclusion proof* is the\n  short list of hashes showing that one record\n  belongs to it.\n- **Discrete-logarithm problem.** The problem of\n  recovering the scalar $d$ from the point $dG$ in\n  an elliptic-curve group. Its presumed hardness\n  is the wall between a public key and the private\n  key behind it.\n- **Commitment.** A short value binding a party to\n  hidden data (*binding*) while revealing nothing\n  about it until it is opened (*hiding*).\n- **Zero-knowledge proof.** A protocol by which\n  one party convinces another that a statement is\n  true while conveying nothing beyond its truth.\n:::\n\n## The statistician's contribution\n\nThree judgements in this chapter are not\nautomated by any cryptographic library, and are\nexactly where quantitative training is decisive.\n\n**1. Distinguishing the two resistance\nproperties and pricing each.** 'The hash is\nsecure' is a tier-four narrative until it is\nresolved into two separate claims with two\nseparate costs. Preimage resistance costs an\nattacker $\\sim 2^{n}$ work; collision resistance\ncosts only $\\sim 2^{n/2}$ by the birthday bound.\nAn analyst who conflates them will overstate the\nsecurity of any scheme whose safety rests on\ncollisions being hard, and the gap is not\nmarginal: for $n = 256$ it is the difference\nbetween $2^{256}$ and $2^{128}$.\n\n**2. Reading a statistical test as evidence for a\nmodel, not proof of a property.** A\nnon-significant chi-square on the first output\nbyte is consistent with uniformity; it does not\nestablish that no structure exists, and it can\nnever rule out a cryptanalytic shortcut that\nleaves the marginal distribution untouched.\nKnowing the difference between 'I failed to reject\nuniformity at the byte margin' and 'the function\nis a random oracle' is the whole of the\nstatistician's discipline here.\n\n**3. Deciding when the cryptography is the wrong\nlayer.** A Merkle root is a genuinely excellent\ncommitment to a locked dataset, and later in this\nchapter we argue for it in exactly one\npublic-health setting, the trial ledger at database\nlock. The same judgement requires saying, candidly,\nthat it needs no blockchain and that most integrity\nproblems are solved more cheaply by a signed hash in\na database. The tool is small; the discipline is\nknowing its scope.\n\n## Hash functions as random oracles\n\nA cryptographic hash function\n$H : \\{0,1\\}^{*} \\to \\{0,1\\}^{n}$ maps an\narbitrary-length input to a fixed $n$-bit digest\n(for SHA-256, $n = 256$). The random-oracle model\nidealises $H$ as a function drawn uniformly at\nrandom from all functions with that signature:\neach distinct input is assigned an independent,\nuniformly random $n$-bit output, and identical\ninputs return identical outputs. No real function\nis a random oracle (a random oracle has no short\ndescription, whereas SHA-256 has a compact one),\nbut the model is the working assumption under\nwhich the rest of the book's probability holds.\nFive properties operationalise it.\n\n- **Determinism.** $H(x)$ depends only on $x$.\n  This is what makes a digest usable as an\n  identifier: the same record always hashes to the\n  same value.\n- **Preimage resistance.** Given a target digest\n  $y$, finding any $x$ with $H(x) = y$ should cost\n  about $2^{n}$ evaluations. This is a brute-force\n  search over the input space with success\n  probability $2^{-n}$ per trial.\n- **Collision resistance.** Finding any pair\n  $x \\neq x'$ with $H(x) = H(x')$ should be\n  infeasible. As we derive below, the birthday\n  bound makes this cost about $2^{n/2}$, far less\n  than preimage resistance.\n- **Avalanche.** A one-bit change in the input\n  flips each output bit independently with\n  probability one half. Under the random-oracle\n  model this is automatic: the perturbed input is\n  a distinct input and so gets an independent\n  output.\n- **Uniformity.** Digests are (marginally)\n  uniformly distributed over $\\{0,1\\}^{n}$, so any\n  fixed window of output bits looks like fair coin\n  flips.\n\nWe begin with the atomic operation, reprised from\n@sec-intro so this chapter stands alone.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(digest)\nh <- function(x) digest(x, algo = 'sha256',\n                        serialize = FALSE)\n\nh('trial-record: patient 001, arm A')\n#> [1] \"3ec839e5d4f9f1294613123c49d35ca5e1321c85a02a2f44008be24692e5d6e8\"\nh('trial-record: patient 001, arm B')\n#> [1] \"0802d479ce38eb4fbd0e6a4d1cd5c688c7c1eb036e7d39b770ff2ab7e466e67e\"\n```\n:::\n\n\n\n\n\n\nThe inputs differ in one character and the digests\nshare no visible structure. Determinism and\navalanche are both on display: re-running the first\nline always returns the same value, yet the\nsingle-character change scrambles the output\ncompletely.\n\n### The birthday bound\n\nPreimage resistance is the easy property to reason\nabout. Each evaluation of $H$ on a fresh input hits\na fixed target with probability $2^{-n}$, so the\nnumber of trials to a first success is geometric\nwith mean $2^{n}$. More useful in practice: to find\nan input whose digest begins with $k$ zero bits,\neach trial succeeds with probability $2^{-k}$, so\nthe expected work is $2^{k}$ evaluations. That last\nstatement is the entire engine of proof-of-work in\n@sec-pow, and it is worth stating precisely now: the\nexpected number of hash evaluations to find a digest\nwith $k$ leading zero bits is $2^{k}$.\n\nCollision resistance is subtler. But how many\nrecords must collide before we worry? For the trial\nledger the question is concrete: how many locked\nrecords can share a digest space before two of them\nreceive the same fingerprint by accident, so that\nthe commitment would silently admit a substitution\nof one for the other? The subtlety is the birthday\nproblem the reader already knows. Draw $m$ inputs\nand hash them. Model the digests, under\nthe random oracle, as $m$ independent draws uniform\non a space of size $N = 2^{n}$. The probability that\nall $m$ digests are distinct is\n\n$$\n\\Pr(\\text{no collision})\n= \\prod_{i=0}^{m-1}\\Bigl(1 - \\frac{i}{N}\\Bigr)\n\\approx \\exp\\!\\Bigl(-\\frac{m(m-1)}{2N}\\Bigr),\n$$\n\nusing $1 - x \\approx e^{-x}$ for small $x$. The\nprobability of at least one collision reaches one\nhalf when the exponent is about $\\ln 2$, that is\nwhen\n\n$$\nm \\approx \\sqrt{2\\ln 2}\\,\\sqrt{N}\n\\approx 1.177 \\cdot 2^{n/2}.\n$$\n\nSo a collision appears after roughly $2^{n/2}$\nhashes, not $2^{n}$. For SHA-256 this is $2^{128}$\nversus $2^{256}$: collision search is the square\nroot of preimage search in cost. This is why\ncollision resistance is the harder property to\ndeliver and the first to fall to cryptanalysis\n(MD5 and SHA-1 were broken on collisions long\nbefore any preimage attack), and why protocol\ndesigners who need only preimage resistance can\nsometimes tolerate a hash that others should not.\n\nWe can watch the birthday bound operate directly.\nTo make collisions findable on a laptop we truncate\nSHA-256 to its first $b$ bits, so $N = 2^{b}$, and\ncount how many random inputs we hash before the\nfirst repeat. The mean first-collision count should\nland near $\\sqrt{\\pi N / 2}$, the birthday\nexpectation.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(202)\n\nfirst_collision <- function(bits) {\n  seen <- character(0)\n  n <- 0L\n  repeat {\n    n <- n + 1L\n    d <- substr(h(paste0('x-', n, '-',\n                         sample(1e9, 1))), 1,\n                bits %/% 4)\n    if (d %in% seen) return(n)\n    seen <- c(seen, d)\n  }\n}\n\nreps <- 300\ndraws16 <- replicate(reps, first_collision(16))\nc(mean_draws = mean(draws16),\n  birthday_expectation = sqrt(pi * 2^16 / 2))\n#>           mean_draws birthday_expectation \n#>             315.1600             320.8484\n```\n:::\n\n\n\n\n\n\nTruncating to 16 bits gives $N = 2^{16} = 65536$\nand a predicted first-collision count of about\n$\\sqrt{\\pi N/2} \\approx 320$. The simulated mean\nlands near that value, confirming the\n$\\sqrt{N} = 2^{n/2}$ scaling as a measured fact\nrather than an asymptotic assertion. Doubling the\ntruncation width to 32 bits would multiply the\nwork by $2^{8} = 256$, the same square-root law\nrunning in reverse.\n\nWe can see the square-root law across several\ndigest widths at once, not only the 16-bit case\nthe simulation used (@fig-birthday-prob).\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(tibble)\nlibrary(dplyr)\nlibrary(tidyr)\n\nPAL <- c('#2a78d6', '#1baf7a', '#eda100', '#008300',\n         '#4a3aa7', '#e34948', '#e87ba4', '#eb6834')\n\nbook_theme <- theme_minimal(base_size = 11) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major = element_line(\n      linewidth = 0.25, colour = 'grey88'),\n    axis.title = element_text(size = 10),\n    legend.position = 'bottom')\n\ncoll_prob <- function(n, b) 1 - exp(-n * (n - 1) / 2^(b + 1))\nn_grid <- 10^seq(0, 6, length.out = 400)\nbday <- tidyr::expand_grid(n = n_grid,\n                           b = c(16L, 24L, 32L)) |>\n  dplyr::mutate(\n    p = coll_prob(n, b),\n    width = factor(paste0(b, '-bit digest'),\n                   levels = c('16-bit digest',\n                              '24-bit digest',\n                              '32-bit digest')))\n\nggplot(bday, aes(n, p, colour = width)) +\n  geom_hline(yintercept = 0.5, linewidth = 0.25,\n             colour = 'grey60', linetype = 2) +\n  geom_line(linewidth = 0.8) +\n  scale_x_log10(breaks = 10^(0:6),\n                labels = c('1', '10', '100', '1e3',\n                           '1e4', '1e5', '1e6')) +\n  scale_colour_manual(values = PAL[1:3], name = NULL) +\n  labs(x = 'number of records n (log scale)',\n       y = 'probability of at least one collision') +\n  book_theme\n```\n\n::: {.cell-output-display}\n![The birthday square-root law across digest widths: each added byte of width postpones the point where an accidental collision becomes likely by a factor of sixteen, since the crossover sits near two to the b over two records.](02-cryptographic-primitives_files/figure-pdf/fig-birthday-prob-1.pdf){#fig-birthday-prob fig-pos='H' width=825}\n:::\n:::\n\n\n\n\n\n\n::: {.callout-note icon=false collapse=true}\n## Check your understanding: 128-bit collisions\n\nA protocol identifies documents by the first 128\nbits of their SHA-256 digest. Roughly how many\ndocuments must exist before a collision becomes\nlikely, and how does that compare to forging a\ndocument that matches one specific existing\nidentifier?\n\nA collision becomes likely at about\n$2^{128/2} = 2^{64}$ documents, by the birthday\nbound. Matching one specific 128-bit identifier\n(a preimage-style search) takes about $2^{128}$\nattempts. The birthday attack is the square root\nof the targeted attack, roughly $2^{64}$ versus\n$2^{128}$, which is the difference between\n'conceivable for a well-resourced adversary' and\n'infeasible'. This is exactly why truncating a\nhash to save space can quietly halve the security\nexponent.\n:::\n\nThe three resistance notions are worth setting\nside by side, since the trial ledger leans on a\ndifferent one for each of its guarantees\n(@tbl-resistance).\n\n| Resistance property | Informal statement | Work factor | Ledger property it underwrites |\n|:---|:---|:---|:---|\n| **Preimage** | Given a digest, find any input that produces it | $\\sim 2^{n}$ | One-wayness: a published root leaks nothing about the records, and the leading-zeros search of proof-of-work |\n| **Second preimage** | Given one record, find a different record with the same digest | $\\sim 2^{n}$ | No single committed record can be swapped for a chosen substitute |\n| **Collision** | Find any two records that share a digest | $\\sim 2^{n/2}$ | Binding of the Merkle root: no record altered, added, or removed without changing the root |\n\n: Preimage, second-preimage, and collision resistance compared, with the work factor for an $n$-bit digest and the trial-ledger property each supports {#tbl-resistance}\n\n### The avalanche effect, measured\n\nThe avalanche property is the claim that flipping\none input bit flips each of the 256 output bits\nindependently with probability one half. We do not\nassume the claim; we validate it, in the sense a\nlaboratory validates an assay against a known\nstandard before trusting the readings it will later\nreturn on unknown samples. If true, the Hamming\ndistance between the two digests (the number of\ndiffering bits out of 256) is a sum of 256\nindependent fair coins, hence\n$\\mathrm{Binomial}(256, 0.5)$, with mean 128 and\nstandard deviation $\\sqrt{256 \\cdot 0.25} = 8$. We\ntest this directly: hash many random strings, flip\ntheir last character, rehash, and record the\nHamming distance in bits.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhex_to_bits <- function(hex) {\n  bytes <- strtoi(\n    substring(hex, seq(1, nchar(hex), 2),\n              seq(2, nchar(hex), 2)),\n    base = 16L)\n  bits <- vapply(bytes,\n    function(b) as.integer(rev(intToBits(b)[1:8])),\n    integer(8))\n  as.vector(bits)\n}\n\nflip_last_char <- function(s) {\n  n <- nchar(s)\n  ch <- substr(s, n, n)\n  repl <- if (ch == 'a') 'b' else 'a'\n  paste0(substr(s, 1, n - 1), repl)\n}\n\nset.seed(1)\nN <- 4000\nstrs <- paste0('msg-', sprintf('%05d', sample(1e6, N)))\nham <- vapply(strs, function(s) {\n  b1 <- hex_to_bits(h(s))\n  b2 <- hex_to_bits(h(flip_last_char(s)))\n  sum(b1 != b2)\n}, numeric(1))\n\nc(mean = mean(ham), sd = sd(ham),\n  binom_sd = sqrt(256 * 0.25))\n#>       mean         sd   binom_sd \n#> 128.045000   8.027645   8.000000\n```\n:::\n\n\n\n\n\n\nThe empirical mean sits near 128 and the standard\ndeviation near the $\\mathrm{Binomial}(256, 0.5)$\nvalue of 8. The histogram, with the normal\napproximation to that binomial overlaid, makes the\nagreement visible.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(tibble)\n\nggplot(tibble(ham = ham), aes(ham)) +\n  geom_histogram(aes(y = after_stat(density)),\n                 bins = 30, fill = 'grey70',\n                 colour = 'white') +\n  stat_function(\n    fun = function(x) dnorm(x, 128, sqrt(64)),\n    linewidth = 0.8) +\n  labs(x = 'Hamming distance (bits changed of 256)',\n       y = 'density',\n       title = 'Avalanche: one input bit flips ~half the output bits')\n```\n\n::: {.cell-output-display}\n![Avalanche effect. Hamming distance between the SHA-256 digests of a string and its one-character perturbation, over 4000 strings, against the Normal approximation to Binomial(256, 0.5).](02-cryptographic-primitives_files/figure-pdf/fig-avalanche-1.pdf){#fig-avalanche fig-pos='H' width=825}\n:::\n:::\n\n\n\n\n\n\nA single input change scrambles the output as if it\nwere independently re-randomised. This is the\navalanche property stated as a measurable fact. We\nshould note the epistemic status carefully: the\nobserved $\\mathrm{Binomial}(256, 0.5)$ shape is\nconsistent with the random-oracle model, and it is\nwhat makes a one-character edit to a trial record\nbetray itself. It is not a proof that SHA-256 has\nno exploitable structure, only that no structure\nshows up in this margin.\n\n### Uniformity of the output\n\nUniformity is the second observable consequence we\nvalidate, and we test it as we would test any\nclaimed random-number generator before admitting it\ninto a simulation. If digests are uniform on\n$\\{0,1\\}^{256}$, then any fixed byte of the output\nis uniform on $\\{0,1,\\dots,255\\}$. We hash 50000\ndistinct inputs, tabulate the first output byte into\nits 256 cells, and apply a chi-square\ngoodness-of-fit test against the uniform\nexpectation.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(2)\nM <- 50000\nfirst_byte <- vapply(seq_len(M), function(i) {\n  strtoi(substr(h(paste0('u-', i)), 1, 2),\n         base = 16L)\n}, numeric(1))\n\nobs <- tabulate(first_byte + 1, nbins = 256)\nchisq <- chisq.test(obs, p = rep(1 / 256, 256))\nc(statistic = unname(chisq$statistic),\n  df = unname(chisq$parameter),\n  p_value = chisq$p.value)\n#>   statistic          df     p_value \n#> 221.4144000 255.0000000   0.9367624\n```\n:::\n\n\n\n\n\n\nThe chi-square statistic sits near its degrees of\nfreedom (255, the mean of a $\\chi^{2}_{255}$) and\nthe p-value is unremarkable. There is no evidence\nagainst uniformity of the first byte, consistent\nwith a hash that behaves as a random oracle. The\nsame caveat applies: this is a test of one marginal,\nand passing it is necessary but nowhere near\nsufficient for cryptographic security. A backdoored\nhash could pass every marginal test we can afford to\nrun while failing catastrophically on a structured\ninput the designer chose in advance.\n\n::: {.callout-important}\n## The sceptic's reflex\n\nMarketing copy calls encryption 'military-grade'\nand systems 'unhackable'. Both phrases are tier-four\nnarrative wearing the cadence of a protocol fact.\n'Military-grade' names no property: AES-256 is\nexcellent and freely available, and the adjective\nadds nothing measurable. 'Unhackable' is stronger\nand worse, because the security of every primitive\nin this chapter is conditional. Collision resistance\nholds only until someone finds a\nbetter-than-birthday attack, exactly as they did for\nMD5 and SHA-1. The correct claim is always\nquantitative and conditional: 'finding a collision\ncosts about $2^{128}$ evaluations under current\ncryptanalysis'. When a vendor omits the number and\nthe condition, demote the claim and ask for both.\n:::\n\n## Merkle trees\n\nA Merkle tree, named for Ralph Merkle who\nintroduced the hash-tree construction, turns a list\nof records into a single digest, the root, such\nthat membership of any one record can be proven\nwith a number of hashes logarithmic in the list\nlength. Leaves are the\nhashes of the records; each internal node is the\nhash of its two children concatenated; the root is\nthe hash at the top. Two facts make the structure\nuseful, and both follow from the hash properties\nabove. First, the root is a binding commitment:\nchanging any record changes its leaf, which by\ncollision resistance changes every ancestor up to\nthe root. Second, proving that a record is in the\ntree requires revealing only the sibling hash at\neach level, $\\lceil \\log_2 m \\rceil$ hashes for $m$\nleaves, not the other $m - 1$ records.\n\nWe implement the tree with the same `h()` from\nabove. When a level has an odd number of nodes we\nduplicate the last one, the common convention that\nkeeps the tree binary. This code is self-contained\nand additional to the verified companion blocks.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhash_pair <- function(a, b) h(paste0(a, b))\n\nmerkle_root <- function(leaves) {\n  level <- vapply(leaves, h, character(1))\n  while (length(level) > 1) {\n    if (length(level) %% 2 == 1) {\n      level <- c(level, level[length(level)])\n    }\n    idx <- seq(1, length(level), by = 2)\n    level <- vapply(idx,\n      function(i) hash_pair(level[i], level[i + 1]),\n      character(1))\n  }\n  unname(level)\n}\n\nset.seed(101)\nrecords <- paste0('trial-record-',\n                  sprintf('%03d', 1:8))\nroot <- merkle_root(records)\nroot\n#> [1] \"08d101e1617dd700396b3d94548e46cff0771c028486560e06b5e140b8991050\"\n```\n:::\n\n\n\n\n\n\nThe eight synthetic records collapse to one 256-bit\nroot. But how would a regulator check a single\nrecord without the whole database? This is what the\ninclusion proof provides. To prove that\n`records[k]` is committed, we walk from its leaf to\nthe root, recording at each level the sibling hash\nand whether it sits to the left or the right. The\nverifier replays that walk from the leaf hash and\nchecks that it reconstructs the published root.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmerkle_proof <- function(leaves, index) {\n  level <- vapply(leaves, h, character(1))\n  proof <- list()\n  i <- index\n  while (length(level) > 1) {\n    if (length(level) %% 2 == 1) {\n      level <- c(level, level[length(level)])\n    }\n    # sibling is to the right of an odd (left) node,\n    # to the left of an even (right) node\n    if (i %% 2 == 1) {\n      proof[[length(proof) + 1]] <-\n        list(hash = unname(level[i + 1]),\n             side = 'right')\n    } else {\n      proof[[length(proof) + 1]] <-\n        list(hash = unname(level[i - 1]),\n             side = 'left')\n    }\n    idx <- seq(1, length(level), by = 2)\n    level <- vapply(idx,\n      function(j) hash_pair(level[j], level[j + 1]),\n      character(1))\n    i <- (i + 1) %/% 2\n  }\n  proof\n}\n\nmerkle_verify <- function(leaf, proof, root) {\n  acc <- h(leaf)\n  for (step in proof) {\n    acc <- if (step$side == 'right')\n             hash_pair(acc, step$hash)\n           else hash_pair(step$hash, acc)\n  }\n  acc == root\n}\n```\n:::\n\n\n\n\n\n\nWe now demonstrate the three properties that make\nthe structure worth its complexity: every genuine\nrecord verifies, a proof is logarithmic in size,\nand a forged record fails.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproof_3 <- merkle_proof(records, 3)\n\nall_verify <- vapply(seq_along(records),\n  function(k) merkle_verify(records[k],\n    merkle_proof(records, k), root),\n  logical(1))\n\nc(all_leaves_verify = all(all_verify),\n  proof_length = length(proof_3),\n  log2_leaves = log2(length(records)),\n  forged_leaf_verifies =\n    merkle_verify('trial-record-forged',\n                  proof_3, root))\n#>    all_leaves_verify         proof_length          log2_leaves \n#>                    1                    3                    3 \n#> forged_leaf_verifies \n#>                    0\n```\n:::\n\n\n\n\n\n\nEvery one of the eight records verifies against the\nroot; the proof for a leaf is three hashes long,\nmatching $\\log_2 8 = 3$; and a forged record\npresented with a genuine proof fails, because its\nleaf hash does not reconstruct the root. A light\nclient holding only the 256-bit root can therefore\nconfirm that a specific record belongs to a\ncommitted set of any size, receiving only\n$\\log_2 m$ hashes and none of the other records.\nThat is the whole basis of simplified payment\nverification in Bitcoin, where a wallet verifies\nthat a transaction is in a block using the block\nheader's Merkle root without downloading the block.\n\nThe proof path is easier seen than described. In\n@fig-merkle-proof we draw the eight-leaf tree of\nthe code above and highlight the inclusion proof\nfor the third leaf.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(tibble)\n\nnodes <- tibble::tribble(\n  ~x,  ~y, ~label,   ~role,\n  1,   0, 'L1',     'other',\n  2,   0, 'L2',     'other',\n  3,   0, 'L3',     'target',\n  4,   0, 'L4',     'sibling',\n  5,   0, 'L5',     'other',\n  6,   0, 'L6',     'other',\n  7,   0, 'L7',     'other',\n  8,   0, 'L8',     'other',\n  1.5, 1, 'H(1:2)', 'sibling',\n  3.5, 1, 'H(3:4)', 'path',\n  5.5, 1, 'H(5:6)', 'other',\n  7.5, 1, 'H(7:8)', 'other',\n  2.5, 2, 'H(1:4)', 'path',\n  6.5, 2, 'H(5:8)', 'sibling',\n  4.5, 3, 'root',   'path')\n\nedges <- tibble::tribble(\n  ~x,  ~y, ~xend, ~yend, ~erole,\n  1,   0, 1.5, 1, 'other',\n  2,   0, 1.5, 1, 'other',\n  3,   0, 3.5, 1, 'path',\n  4,   0, 3.5, 1, 'sibling',\n  5,   0, 5.5, 1, 'other',\n  6,   0, 5.5, 1, 'other',\n  7,   0, 7.5, 1, 'other',\n  8,   0, 7.5, 1, 'other',\n  1.5, 1, 2.5, 2, 'sibling',\n  3.5, 1, 2.5, 2, 'path',\n  5.5, 1, 6.5, 2, 'other',\n  7.5, 1, 6.5, 2, 'other',\n  2.5, 2, 4.5, 3, 'path',\n  6.5, 2, 4.5, 3, 'sibling')\n\ntxt_col <- ifelse(nodes$role %in% c('target', 'path'),\n                  'white', 'grey15')\nnodes$role <- factor(nodes$role,\n  levels = c('target', 'path', 'sibling', 'other'),\n  labels = c('target leaf', 'recomputed path',\n             'proof sibling', 'uninvolved'))\n\nfill_named <- c('target leaf' = '#1d5a9e',\n                'recomputed path' = '#2a78d6',\n                'proof sibling' = '#eda100',\n                'uninvolved' = '#9a9a92')\nedge_cols <- c(path = '#2a78d6', sibling = '#eda100',\n               other = 'grey80')\n\nggplot() +\n  geom_segment(data = edges,\n    aes(x = x, y = y, xend = xend, yend = yend,\n        colour = erole),\n    linewidth = 0.7, show.legend = FALSE) +\n  scale_colour_manual(values = edge_cols) +\n  geom_tile(data = nodes, aes(x = x, y = y, fill = role),\n            width = 0.82, height = 0.55, colour = 'white') +\n  geom_text(data = nodes, aes(x = x, y = y, label = label),\n            colour = txt_col, size = 2.5) +\n  scale_fill_manual(values = fill_named, name = NULL) +\n  expand_limits(x = c(0.4, 8.6), y = c(-0.4, 3.5)) +\n  theme_void(base_size = 11) +\n  theme(legend.position = 'bottom')\n```\n\n::: {.cell-output-display}\n![Inclusion proof for the third of eight leaves. The verifier holds only the target leaf in dark blue and the three sibling hashes in amber, and rehashes up the blue path to reconstruct the root; the six uninvolved records in grey are never revealed.](02-cryptographic-primitives_files/figure-pdf/fig-merkle-proof-1.pdf){#fig-merkle-proof fig-pos='H' width=825}\n:::\n:::\n\n\n\n\n\n\n::: {.callout-note icon=false collapse=true}\n## Check your understanding: proof size and privacy\n\nA Merkle tree commits to one million records. How\nmany hashes does an inclusion proof contain, and\nwhich of the other records does the verifier learn\nabout?\n\nThe proof contains\n$\\lceil \\log_2 10^{6} \\rceil = 20$ hashes. The\nverifier learns nothing about the contents of the\nother records: each proof step reveals only a\nsibling digest, and by preimage resistance a digest\ndoes not disclose the record that produced it. This\ncombination, membership provable in 20 hashes and\nno leakage of the rest, is precisely what lets a\ndata custodian publish a root as a commitment while\nkeeping the underlying records confidential.\n:::\n\n### Public-health application: committing to a locked trial dataset\n\nWe return now to the problem with which the chapter\nopened, for here the cryptography is genuinely the\nright tool. At database lock the trial ledger fixes\nits dataset before unblinding and analysis. The\nrecurring integrity question is whether any record\nwas altered after lock, for example to remove an\ninconvenient adverse event or to adjust an outcome\nin a direction favourable to the sponsor. We build a\nMerkle tree over the hashes of the locked records\nand publish the root, whether in a journal, a\nregistry, a timestamping service, or simply a\nwidely-witnessed public post. The root is a 256-bit\ncommitment to the entire dataset. Later, any party,\nand in particular the regulator of the opening\nscenario, may be handed a single record together\nwith a logarithmic inclusion proof and verify that\nthe record was in the locked set; and by collision\nresistance no record can be altered, added, or\nremoved without changing the published root and\nthereby exposing the tampering. The records\nthemselves never need to be disclosed in order to\nmake the commitment, so patient confidentiality is\npreserved, since the published root reveals nothing\nabout the data.\n\n@fig-tamper traces what the regulator sees when a\nsingle record is altered after lock.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(tibble)\n\ntnodes <- tibble::tribble(\n  ~x,  ~y, ~label,   ~role,\n  1,   0, 'L1',     'other',\n  2,   0, 'L2',     'other',\n  3,   0, 'L3',     'other',\n  4,   0, 'L4',     'other',\n  5,   0, 'L5',     'other',\n  6,   0, 'L6*',    'tampered',\n  7,   0, 'L7',     'other',\n  8,   0, 'L8',     'other',\n  1.5, 1, 'H(1:2)', 'other',\n  3.5, 1, 'H(3:4)', 'other',\n  5.5, 1, 'H(5:6)', 'prop',\n  7.5, 1, 'H(7:8)', 'other',\n  2.5, 2, 'H(1:4)', 'other',\n  6.5, 2, 'H(5:8)', 'prop',\n  4.5, 3, 'root',   'prop')\n\ntedges <- tibble::tribble(\n  ~x,  ~y, ~xend, ~yend, ~erole,\n  1,   0, 1.5, 1, 'other',\n  2,   0, 1.5, 1, 'other',\n  3,   0, 3.5, 1, 'other',\n  4,   0, 3.5, 1, 'other',\n  5,   0, 5.5, 1, 'other',\n  6,   0, 5.5, 1, 'prop',\n  7,   0, 7.5, 1, 'other',\n  8,   0, 7.5, 1, 'other',\n  1.5, 1, 2.5, 2, 'other',\n  3.5, 1, 2.5, 2, 'other',\n  5.5, 1, 6.5, 2, 'prop',\n  7.5, 1, 6.5, 2, 'other',\n  2.5, 2, 4.5, 3, 'other',\n  6.5, 2, 4.5, 3, 'prop')\n\nttxt <- ifelse(tnodes$role %in% c('tampered', 'prop'),\n               'white', 'grey15')\ntnodes$role <- factor(tnodes$role,\n  levels = c('tampered', 'prop', 'other'),\n  labels = c('altered record', 'changed ancestry',\n             'unchanged'))\n\ntfill <- c('altered record' = '#e34948',\n           'changed ancestry' = '#e34948',\n           'unchanged' = '#9a9a92')\ntedge <- c(prop = '#e34948', other = 'grey80')\n\nggplot() +\n  geom_segment(data = tedges,\n    aes(x = x, y = y, xend = xend, yend = yend,\n        colour = erole),\n    linewidth = 0.7, show.legend = FALSE) +\n  scale_colour_manual(values = tedge) +\n  geom_tile(data = tnodes, aes(x = x, y = y, fill = role),\n            width = 0.82, height = 0.55, colour = 'white') +\n  geom_text(data = tnodes, aes(x = x, y = y, label = label),\n            colour = ttxt, size = 2.5) +\n  annotate('text', x = 4.5, y = 3.6,\n           label = 'root no longer matches the regulator copy',\n           colour = '#e34948', size = 2.8) +\n  scale_fill_manual(values = tfill, name = NULL) +\n  expand_limits(x = c(0.4, 8.6), y = c(-0.4, 3.9)) +\n  theme_void(base_size = 11) +\n  theme(legend.position = 'bottom')\n```\n\n::: {.cell-output-display}\n![Tamper propagation. A single post-lock edit to one record changes its leaf hash, and by collision resistance the change cascades up every ancestor in red until the root no longer matches the value the regulator holds.](02-cryptographic-primitives_files/figure-pdf/fig-tamper-1.pdf){#fig-tamper fig-pos='H' width=825}\n:::\n:::\n\n\n\n\n\n\n::: {.callout-warning}\n## This needs no blockchain\n\nThe mechanism above is a hash tree and a published\nroot. It requires no consensus protocol, no tokens,\nno mining, and no chain. A single trustworthy\npublication of the root at lock is sufficient,\nbecause the security rests entirely on collision\nresistance, not on distributed agreement. A\nblockchain would add value only if no party could be\ntrusted even to publish the root honestly and\npromptly, which is rarely the situation in a\nregulated trial with an established registry. This\nis the falsifiability discipline of @sec-intro in\naction: the useful primitive here is the Merkle\ncommitment, and attaching 'blockchain' to it is\ntier-four narrative unless a specific trust failure\nis named that only consensus can repair. The\ntimestamping lineage that predates blockchains\n[@haber1991timestamp] made exactly this point:\ntamper-evident chronology is a hashing problem, and\nwas solved as one.\n\nIt was also, and this is the part the promotional\nliterature omits, *standardised* as one. The\nInternet time-stamping protocol of 2001 accepts a\nhash, never the underlying record, and returns a\nsigned token establishing that the datum existed\nbefore a stated moment [@rfc3161]; the certificate\ntransparency standard supplies an append-only Merkle\nlog with logarithmic inclusion and consistency\nproofs, and has run at internet scale for over a\ndecade [@rfc6962; @trillian]. Between them these\ndeliver every property our locked-dataset example\nrequires: proof of existence, proof of inclusion,\nand proof that the log was only ever appended to.\nBitcoin's own data structure, as its academic\ngenealogy makes plain, was borrowed from this\nlineage with little modification\n[@narayanan2017pedigree], which means the\nhash-linked log is separable from the consensus\nmachinery and can be had without it. A trial ledger\nthat names no adversary the notary cannot handle is\ntherefore not buying tamper-evidence with its\nblockchain; it already had tamper-evidence, and is\nbuying only expense. Readers who wish to see the\nregulatory question taken seriously, control by\ncontrol against the electronic-records requirements\nof 21 CFR Part 11, should consult @oakley2023scrybe,\nwhich is nearly alone in the literature in doing so,\nand which concludes that the public chains fail\nthose controls.\n:::\n\n## Digital signatures over elliptic curves\n\nHashing makes the trial ledger tamper-evident;\nsignatures make its entries attributable. The Merkle\ncommitment settles whether a record was altered, but\nit says nothing about who entered it. In the trial\nledger we also wish to know which site coordinator\nrecorded a given eCRF entry, and to have that\nattribution be checkable by a party, such as the\nregulator, who trusts none of the coordinators in\nadvance. The public-key idea\n[@diffie1976new; @rivest1978method] supplies exactly\nthis: a signer holds a private scalar and publishes\na corresponding public key, such that anyone can\nverify a signature but only the holder of the\nprivate key can produce one. A coordinator who signs\neach entry with a site-held private key makes\nauthorship of that entry cryptographically checkable,\nand forging an attribution is as hard as the\ndiscrete-logarithm problem we come to below.\nBlockchains realise this over elliptic-curve groups,\nand the group that matters for Bitcoin and much of\nEthereum is\nsecp256k1: the points $(x, y)$ satisfying\n$y^{2} = x^{3} + 7$ over the prime field\n$\\mathbb{F}_{p}$ for a specific 256-bit prime $p$,\ntogether with a point at infinity as the identity.\nThese points form a cyclic group of prime order,\ngenerated by a fixed base point $G$.\n\nThe group law is geometric: to add two points, draw\nthe line through them, find its third intersection\nwith the curve, and reflect across the $x$-axis. A\nprivate key is a scalar $d$; the public key is the\npoint $Q = dG$, meaning $G$ added to itself $d$\ntimes (computed efficiently by\ndouble-and-add, not $d$ literal additions).\nRecovering $d$ from $Q$ and $G$ is the elliptic-curve\ndiscrete logarithm problem, believed to require\nabout $2^{128}$ operations for secp256k1. That\nasymmetry, easy to multiply the base point by a\nscalar, infeasible to invert, is the wall between a\npublic key and its private scalar.\n\nTo make the group concrete we verify the one axiom\nthat is not obvious from the geometry, associativity,\non a small curve $y^{2} = x^{3} + ax + b$ over\n$\\mathbb{F}_{97}$. The arithmetic is identical in\nkind to secp256k1; only the field is small enough to\nenumerate.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_inv <- function(a, p) {\n  a <- a %% p\n  for (x in 1:(p - 1)) if ((a * x) %% p == 1) return(x)\n  stop('no inverse')\n}\n\n# Curve: y^2 = x^3 + a x + b over F_p,\n# with the point at infinity as NA.\nec_add <- function(P, Q, a, p) {\n  if (all(is.na(P))) return(Q)\n  if (all(is.na(Q))) return(P)\n  if (P[1] == Q[1] && (P[2] + Q[2]) %% p == 0)\n    return(c(NA, NA))\n  if (all(P == Q)) {\n    m <- ((3 * P[1]^2 + a) * mod_inv(2 * P[2], p)) %% p\n  } else {\n    m <- ((Q[2] - P[2]) *\n          mod_inv((Q[1] - P[1]) %% p, p)) %% p\n  }\n  xr <- (m^2 - P[1] - Q[1]) %% p\n  yr <- (m * (P[1] - xr) - P[2]) %% p\n  c(xr %% p, yr %% p)\n}\n\np <- 97; a <- 2; b <- 3\npts <- do.call(rbind, Filter(Negate(is.null),\n  lapply(0:(p - 1), function(x) {\n    y2 <- (x^3 + a * x + b) %% p\n    ys <- which(((0:(p - 1))^2 %% p) == y2) - 1\n    if (length(ys)) cbind(x, ys) else NULL\n  })))\n\nP <- pts[3, ]; Q <- pts[5, ]; R <- pts[9, ]\nlhs <- ec_add(ec_add(P, Q, a, p), R, a, p)\nrhs <- ec_add(P, ec_add(Q, R, a, p), a, p)\nlist(P = P, Q = Q, R = R,\n     associative = isTRUE(all.equal(lhs, rhs)),\n     result = lhs)\n#> $P\n#>  x ys \n#>  1 43 \n#> \n#> $Q\n#>  x ys \n#>  3  6 \n#> \n#> $R\n#>  x ys \n#> 10 21 \n#> \n#> $associative\n#> [1] TRUE\n#> \n#> $result\n#> ys ys \n#> 80 87\n```\n:::\n\n\n\n\n\n\nAssociativity holds: $(P + Q) + R$ equals\n$P + (Q + R)$. With associativity, an identity, and\ninverses (the reflection of a point), the points form\nan abelian group, and scalar multiplication $dG$ is\nwell-defined. Inverting it, the discrete-log problem,\nis the hardness the signature scheme rests on.\n\n### ECDSA, Schnorr, and aggregation\n\nTwo signature schemes run on this group. ECDSA is the\nscheme Bitcoin launched with: to sign a message\ndigest $m$ with private key $d$, the signer draws a\nper-signature nonce $k$, computes a point $kG$, and\nproduces a pair $(r, s)$ where the algebra binds\n$m$, $d$, $r$, and $k$. ECDSA works, but its security\nis fragile in one notorious way: reusing or leaking\nthe nonce $k$ across two signatures leaks the private\nkey algebraically, and a biased $k$ leaks it\nstatistically. The nonce is a place where a subtle\nrandom-number-generator flaw becomes a total key\ncompromise, which is a lesson in why the uniformity\ntests earlier in this chapter are not academic.\n\nSchnorr signatures, named for Claus Schnorr who\nproposed them [@schnorr1991efficient], achieve the\nsame authentication with a cleaner algebraic\nstructure. Because the Schnorr verification equation\nis linear in the key and the nonce, signatures and\nkeys can be aggregated: several signers can produce a\nsingle signature valid for the sum of their public\nkeys, and a batch of signatures can be verified\ntogether faster than one at a time. Aggregation is\nattractive for a blockchain because signatures\ndominate transaction size and verification cost;\ncombining $n$ signatures into one shrinks both. This\nlinearity is why Bitcoin's Taproot upgrade adopted\nSchnorr.\n\nBLS signatures, named for Boneh, Lynn and Shacham\n[@boneh2001short], push aggregation further using a\npairing on a suitable curve. A BLS\nsignature is a single group element, and, crucially,\nsignatures from many signers on the same message\naggregate into one short signature verifiable against\nthe aggregate public key. This is the property that\nmakes BLS the signature scheme of choice for\nproof-of-stake consensus in @sec-pos, where thousands\nof validators attest to each block and the ability to\ncompress thousands of signatures into one is what\nkeeps the protocol tractable.\n\n::: {.callout-note icon=false collapse=true}\n## Check your understanding: why aggregation matters\n\nA proof-of-stake block collects attestations from\n10000 validators. Contrast the verification burden\nif each attestation carried an independent ECDSA\nsignature versus a single BLS-aggregated signature,\nand name the property that makes aggregation\npossible.\n\nWith independent ECDSA signatures the verifier\nperforms 10000 separate verifications and the block\ncarries 10000 signatures, roughly 640 KB at 64 bytes\neach. With BLS aggregation the 10000 signatures on\nthe shared attestation collapse to one group element\nand one aggregate public key, verified in a single\npairing check. The enabling property is linearity of\nthe signature scheme in the key and message: BLS (and\nSchnorr) verification equations are linear, so sums of\nkeys and signatures verify together, whereas ECDSA's\nequation is not, so its signatures do not aggregate.\nThis is the difference between a consensus protocol\nthat scales to thousands of validators and one that\ndoes not.\n:::\n\n### A note on quantum threats\n\nWe should not close the discussion of signatures\nwithout asking how durable their hardness is, for a\nquestion that once seemed academic has become a\ngenuine design consideration. What would a\nlarge-scale quantum computer do to the primitives of\nthis chapter? The answer divides sharply, and the\ndivision is the practical point. Shor's algorithm\nsolves the discrete-logarithm and integer-\nfactorisation problems in polynomial time, and these\nare precisely the problems on which ECDSA and RSA\nrest. A sufficiently large quantum computer would\ntherefore recover a private key from its public key\nand forge signatures at will, which is to say that\nthe public-key signatures of this chapter would fail\ncompletely rather than merely weaken. Hash functions\nfare far better. Grover's algorithm speeds an\nunstructured search only quadratically, so inverting\nan $n$-bit hash falls from about $2^{n}$ to about\n$2^{n/2}$ work; a hash loses roughly a square-root\nfactor of its security and no more, which for\nSHA-256 still leaves a comfortable $2^{128}$. The\nanalysis of quantum attacks on Bitcoin by Aggarwal\nand colleagues [@aggarwal2018quantum] works these\nasymmetries through in detail and reaches the same\nqualitative conclusion: signatures are the exposed\nsurface, and hashes are relatively robust.\n\nFor a health ledger the implication is not\nhypothetical, and it turns on the longevity of the\nrecord. A trial ledger is a long-lived object: a\nsignature made today to attribute an eCRF entry may\nneed to remain unforgeable for decades, through the\narchival life of the trial and any later re-analysis\nor litigation. This is the 'harvest now, forge later'\nhorizon, in which an adversary records today's public\nkeys and signatures and waits for the cryptographic\nera to turn, at which point yesterday's unforgeable\nattributions become forgeable. The horizon is genuine\nfor any ledger meant to outlive the current generation\nof public-key cryptography, and it argues, on the one\nhand, for preferring hash-based commitments wherever a\nhash will do the work, since these are the resilient\nprimitive, and, on the other, for designing the\nsignature layer to be replaceable, so that a migration\nto a post-quantum scheme can be carried out without\ndiscarding the ledger. We do not attempt to recommend\na specific post-quantum signature here; the field is\nstill settling, and the prudent posture, in our view,\nis to keep the option open rather than to commit early.\n\n## Commitments and zero-knowledge\n\nThe Merkle root is one instance of a commitment: a\nshort value that binds a party to hidden data\n(binding), while revealing nothing about it until\nopened (hiding). The same idea generalises. A\ncommitment scheme lets a party publish a commitment\nnow and reveal the committed value later, with the\nscheme guaranteeing the value cannot be changed in\nbetween. The binding property rests on collision\nresistance, exactly as the Merkle root does, and the\nhiding property on the one-wayness of the hash, so a\ncommitment asks of the reader nothing that the\npresent chapter has not already supplied.\n\nA commitment fixes a value, but it does not, by\nitself, let one demonstrate anything about that value\nwhile it remains hidden. That further step, proving a\nproperty of committed data without opening it, is the\nprovince of the zero-knowledge proof, to which we now\nturn.\n\n## Zero-knowledge proofs\n\nWe begin with a claim that sounds paradoxical and is\nnot. Can one party convince another that a statement\nis true while conveying nothing whatever beyond its\ntruth, not even the reason it is true? The\naffirmative answer, formalised by Goldwasser, Micali\nand Rackoff [@goldwasser1989knowledge], whose study\nof the knowledge complexity of interactive proof\nsystems founded the subject, is among the deeper\nresults of modern cryptography, and it rests on\nthree properties that a\nreader trained in statistics will find unusually\ncongenial. Consider a prover, who claims to hold a\nwitness to some statement, and a verifier, who will\naccept or reject after an exchange of messages. An\ninteractive proof system is required to satisfy three\nconditions.\n\n- **Completeness.** If the statement is true and the\n  prover is honest, the verifier accepts with\n  overwhelming probability. An honest prover in\n  possession of the witness is essentially never\n  turned away.\n- **Soundness.** If the statement is false, then no\n  prover, however devious, can make the verifier\n  accept except with some small probability, the\n  soundness error. This error is not a defect to be\n  apologised for; it is the very quantity the\n  construction controls, and repetition drives it\n  toward zero.\n- **Zero-knowledge.** The verifier learns nothing\n  from the exchange beyond the truth of the\n  statement, in the precise sense that whatever the\n  verifier sees could have been simulated, without\n  the prover at all, from the statement alone.\n\nThe property that repays statistical attention is\nsoundness, and it is worth dwelling on why. A\nsoundness error of $\\varepsilon$ means that a cheating\nprover, one who does not hold the witness, slips a\nfalse statement past the verifier with probability at\nmost $\\varepsilon$ on a single run. But how small must\n$\\varepsilon$ be? Here the analogy to hypothesis\ntesting is exact rather than decorative. The verifier\nis running a test whose null hypothesis is 'the prover\ndoes not know the witness', and the soundness error is\nprecisely the type-one error rate, the probability of\naccepting a false claim. A single round of a protocol\nwhose challenge is one bit has soundness error one\nhalf, which no statistician would accept as a test.\nThere are then two routes to a small error, and they\nare interchangeable. One may repeat the protocol:\nbecause the rounds are independent, $t$ repetitions\ndrive the soundness error to $2^{-t}$, the geometric\ndecay that @fig-zk-soundness traces against the\nconventional 0.05 level. Or one may widen the\nchallenge within a single round, so that a prover who\ncan answer only one of the $\\lvert C \\rvert$ possible\nchallenges for a given commitment succeeds with\nprobability at most $1 / \\lvert C \\rvert$. The Schnorr\nprotocol below takes the second route, drawing its\nchallenge from the whole scalar field, and so attains\na negligible soundness error in one round with no\nrepetition at all; the repetition picture belongs to\nits small-challenge cousins. One chooses whichever\nroute the setting favours to meet the tolerance\ndemanded.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(tibble)\n\nPAL <- c('#2a78d6', '#1baf7a', '#eda100', '#008300',\n         '#4a3aa7', '#e34948', '#e87ba4', '#eb6834')\n\nbook_theme <- theme_minimal(base_size = 11) +\n  theme(\n    panel.grid.minor = element_blank(),\n    panel.grid.major = element_line(\n      linewidth = 0.25, colour = 'grey88'),\n    axis.title = element_text(size = 10),\n    legend.position = 'bottom')\n\nrounds <- 0:12\nsound <- tibble::tibble(t = rounds, err = (1 / 2)^rounds)\n\nggplot(sound, aes(t, err)) +\n  geom_hline(yintercept = 0.05, linewidth = 0.25,\n             colour = 'grey60', linetype = 2) +\n  geom_line(linewidth = 0.8, colour = PAL[1]) +\n  geom_point(size = 1.6, colour = PAL[1]) +\n  annotate('text', x = 9, y = 0.075,\n           label = 'conventional 0.05 level',\n           colour = 'grey40', size = 2.8) +\n  scale_y_log10(breaks = 10^(0:-4),\n                labels = c('1', '0.1', '0.01',\n                           '0.001', '0.0001')) +\n  scale_x_continuous(breaks = seq(0, 12, 2)) +\n  labs(x = 'number of independent rounds t',\n       y = 'soundness error (log scale)') +\n  book_theme\n```\n\n::: {.cell-output-display}\n![Soundness error under repetition. A sigma-protocol with per-round soundness error one half sees that error fall geometrically as two to the minus t over t independent rounds, crossing the conventional 0.05 level between the fourth and fifth round.](02-cryptographic-primitives_files/figure-pdf/fig-zk-soundness-1.pdf){#fig-zk-soundness fig-pos='H' width=825}\n:::\n:::\n\n\n\n\n\n\nThe abstraction becomes concrete in the oldest and\ncleanest example, the identification protocol of\nSchnorr [@schnorr1991efficient]. Recall the\nelliptic-curve group of the preceding section, with\nbase point $G$ of prime order and the\ndiscrete-logarithm problem, recovering $d$ from\n$Q = dG$, believed hard. A prover wishes to convince a\nverifier that she knows the private scalar $d$ behind\na public key $Q = dG$, without revealing $d$. The\nexchange has the three-move shape that names this\nfamily of protocols, the sigma-protocol, after the\nshape of its message flow.\n\n- **Commitment.** The prover draws a fresh random\n  scalar $r$, computes the point $R = rG$, and sends\n  $R$. The scalar $r$ is a secret nonce, and its role\n  is exactly that of a commitment: it binds the prover\n  to a value she cannot afterward change.\n- **Challenge.** The verifier draws a random scalar\n  $c$ and returns it. This is the public coin, chosen\n  after the commitment is fixed.\n- **Response.** The prover sends $s = r + c\\,d$,\n  computed with the secret scalars, and the verifier\n  accepts if $sG$ equals $R + cQ$.\n\nThe algebra closes because\n$sG = (r + c\\,d)G = rG + c(dG) = R + cQ$, so an honest\nprover always passes, which is completeness. Soundness\nis the interesting direction: a prover who does not\nknow $d$ cannot in general answer a challenge she could\nnot predict, and one can show that a prover able to\nanswer two different challenges for the same\ncommitment $R$ would thereby reveal $d$ outright, which\nis the knowledge-extraction argument that gives the\nsoundness its teeth. The protocol is zero-knowledge\nbecause the triple $(R, c, s)$ can be simulated without\n$d$ at all: choose $s$ and $c$ at random and set\n$R = sG - cQ$, and the resulting transcript is\ndistributed exactly as a genuine run, carrying no\ninformation about the secret. That last observation is\nthe whole content of the zero-knowledge property in\nminiature.\n\nOne inconvenience remains. The protocol as described\nis interactive, in that the verifier must be present to\nissue the challenge $c$. But what if the prover wishes\nto leave behind a proof that anyone can check later,\nwith no live verifier at all? The device that removes\nthe verifier is the Fiat-Shamir heuristic, and its\nintuition is simple. The challenge is meant\nto be unpredictable to the prover before she commits,\nand a cryptographic hash, which the earlier part of\nthis chapter established behaves as a random oracle,\nsupplies exactly such unpredictability. We replace the\nverifier's coin with $c = H(R, \\text{statement})$, the\nhash of the commitment together with the statement\nbeing proved. The prover cannot steer the output of the\nhash, and so cannot choose $R$ to suit a favourable\n$c$; the interactive protocol collapses to a single\nnon-interactive proof, the pair $(R, s)$, that any\nparty can verify by recomputing the challenge. This is,\nincidentally, how the interactive identification scheme\nbecomes the Schnorr signature met earlier, and it is\none more reason the random-oracle tests of this chapter\nare load-bearing rather than ornamental.\n\nThe Schnorr proof is small and quick, but its statement\nis fixed and simple, namely knowledge of one discrete\nlogarithm. The ambition of the last decade has been to\nprove, just as compactly, that an arbitrary computation\nwas carried out correctly, that a whole batch of\ntransactions is valid, or that a committed record\nsatisfies an elaborate predicate. The proofs that\nachieve this go by the name of succinct non-interactive\narguments of knowledge, or SNARKs. What does 'succinct'\nbuy? It is the property that the proof is far smaller\nthan the computation it attests to and can be checked\nin far less time than re-executing that computation\nwould take, so that a verifier who would need hours to\nredo the work can instead check a proof of a few\nhundred bytes in milliseconds. Ben-Sasson, Chiesa,\nTromer and Virza [@bensasson2014snark] gave a\nconstruction for a general von Neumann computer\narchitecture, bringing arbitrary programs within reach;\nGroth [@groth2016size] produced the compact\npairing-based scheme, with proofs of constant size,\nthat is now widely deployed; and Ben-Sasson and\ncolleagues [@bensasson2018stark] later introduced\ntransparent STARKs, which dispense with the trusted\nsetup that pairing-based SNARKs require and rest their\nsecurity on hashes alone, at the cost of somewhat larger\nproofs. The application that turned these ideas from\ntheory into consequence was Zerocash\n[@bensasson2014zerocash], which used succinct proofs to\nbuild a payment system in which a transaction proves its\nown validity, that its inputs and outputs balance and\nthe spender is authorised, while revealing neither\nsender, receiver, nor amount, and so turned\nzero-knowledge into private payments.\n\nWe should be candid about the boundary of our\ncompetence here. The internal machinery of these\nconstructions, the arithmetic circuits, the polynomial\ncommitments, the elliptic-curve pairings, is a\nsubstantial body of cryptographic engineering that lies\nwell beyond the scope of this book. We cite these\nsystems as an interface and not as an implementation:\nwhat matters for our purposes is the guarantee they\nexpose, a short proof that a stated computation was\nperformed correctly, and not the mechanism by which\nthey attain it.\n\nWhy should a book concerned with public-health data\nattend to any of this? Because zero-knowledge is the\nnatural language for privacy-preserving health\nanalytics, and the connection is not merely\nmetaphorical. To illustrate, consider a multi-site\ntrial with an eligibility protocol under which a\nprospective participant must fall within an age band\nand carry a laboratory value in a specified range. A\nsite can, in principle, prove to the coordinating\ncentre that a given individual satisfies these\ncriteria, that the age lies in one interval and the\nlab value in another, without transmitting the date of\nbirth or the laboratory result itself. The statement\n'this record satisfies the predicate' is established;\nthe record stays home. Broadened, this is the same\naspiration as secure multiparty computation and\nfederated analysis, in which a statistic, a regression\ncoefficient or a pooled prevalence, is computed jointly\nacross institutions while each retains custody of its\nraw data and surrenders none of it.\n\nThe analogy must be drawn with care, for it is easily\noverstated. A zero-knowledge proof establishes the\ntruth of a statement about data that has already been\ncommitted; it does not, on its own, compute a joint\nstatistic across parties. Proving that each site's\nrecord satisfies a predicate is a different operation\nfrom combining those records into a pooled estimate,\nand the latter is the province of secure multiparty\ncomputation proper, of which zero-knowledge proofs are\na component rather than a synonym. We flag the\ndistinction because conflating the two is a common\nroute to overstating what a privacy-preserving pipeline\nactually delivers. The constructions themselves we take\nno further here, and the reader who wishes to pursue\nthem is referred to the primary sources named above.\n\n::: {.callout-note icon=false collapse=true}\n## Check your understanding: soundness as type-one error\n\nA verifier runs a single round of an interactive proof\nwhose soundness error is one half. A statistician\nobjects that a test which wrongly accepts a false claim\nhalf the time is worthless. How is the objection\nanswered, and how many independent rounds are needed to\ndrive the probability of accepting a false claim below\none in a million?\n\nThe objection is answered by repetition. The soundness\nerror is exactly a type-one error rate, and because the\nrounds are independent, $t$ of them multiply the\nper-round error to $(1/2)^{t}$. To fall below\n$10^{-6}$ we need $(1/2)^{t} < 10^{-6}$, that is\n$t > 6 / \\log_{10} 2 \\approx 19.9$, so twenty rounds\nsuffice. This is the same logic by which one lowers a\nsignificance threshold, and it is why a single round\nwith soundness error one half is not an embarrassment\nbut a starting point: one buys as much soundness as the\nsetting requires by paying in rounds.\n:::\n\nBefore the worked example we gather the four\nprimitives of the chapter into one view, each with\nthe guarantee it provides and, as important, the\nguarantee it does not (@tbl-primitives).\n\n| Primitive | Guarantee | Role in the trial ledger | What it cannot do |\n|:---|:---|:---|:---|\n| **Hash** | Deterministic one-way fingerprint | Detects any change to a record | Attribute authorship, or reveal what changed beyond the digest |\n| **Digital signature** | Authenticity and non-repudiation | Attributes each eCRF entry to a site coordinator | Prove integrity of anything beyond what was signed, or establish time |\n| **Merkle tree** | Logarithmic membership proof over a binding root | Lets an auditor verify one record against the root without the dataset | Say who entered a record, or when |\n| **Commitment** | Binding and hiding | Publishes a value now to be revealed later, fixed in between | Prove a property of the hidden value, which needs zero-knowledge |\n\n: The four primitives of this chapter, the guarantee each provides, its role in the trial ledger, and its limits {#tbl-primitives}\n\n## Worked example\n\nTo illustrate, consider the trial ledger at its lock\ndate, with the pieces now assembled into one\nend-to-end analysis of the problem with which we\nbegan. We commit to the locked dataset, prove one\nrecord's membership to an auditor, and confirm that\nany tampering is caught by the published root. This\nis the trial-ledger application of the previous\nsection, run as code on a SYNTHETIC locked dataset\nstanding in for the real trial records.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(303)\n\n# SYNTHETIC locked trial dataset: one row per\n# subject, serialised to a canonical string.\nlocked <- data.frame(\n  subject = sprintf('S%04d', 1:16),\n  arm = sample(c('A', 'B'), 16, replace = TRUE),\n  outcome = rbinom(16, 1, 0.3),\n  stringsAsFactors = FALSE\n)\nrecord_strings <- with(locked,\n  paste(subject, arm, outcome, sep = '|'))\n\npublished_root <- merkle_root(record_strings)\n\n# An auditor is handed subject 7's record plus a\n# proof, and verifies membership against the\n# published root alone.\nk <- 7\naudit_ok <- merkle_verify(\n  record_strings[k],\n  merkle_proof(record_strings, k),\n  published_root)\n\n# Someone alters subject 12's outcome after lock.\ntampered <- record_strings\ntampered[12] <- paste0(tampered[12], '-edited')\n\nc(auditor_confirms_membership = audit_ok,\n  proof_hashes = length(merkle_proof(record_strings, k)),\n  tamper_changes_root =\n    merkle_root(tampered) != published_root)\n#> auditor_confirms_membership                proof_hashes \n#>                           1                           4 \n#>         tamper_changes_root \n#>                           1\n```\n:::\n\n\n\n\n\n\nThe auditor confirms subject 7's record with a\nfour-hash proof (the tree over 16 leaves has depth\nfour) and never sees the other fifteen records. The\npost-lock edit to subject 12 changes the root, so\nanyone holding the originally published root detects\nthat the dataset is no longer the one committed to.\nThe guarantee is exactly as strong as collision\nresistance, which the birthday analysis priced at\nabout $2^{128}$ work, and no stronger. It is also, as\nthe warning above insisted, achieved with no\nblockchain: a hash tree and one honest publication.\n\n## Collaborating with an LLM\n\nLanguage models are fluent about cryptography and\nconfidently wrong at its edges, which is precisely\nwhere security lives. They are of use in\naccelerating routine work, provided the parts that\nmatter are verified against a primary source.\n\n**Prompt.** 'Write an R function to compute a Merkle\nroot and an inclusion proof using the digest\npackage.'\n\n*Watch for:* the odd-node convention (duplicate the\nlast node, or promote it unchanged?), off-by-one\nerrors in sibling indexing, and whether the proof\nrecords left/right order at all. A verifier that\nignores order will accept proofs for the wrong\nposition.\n\n*Verification:* the structural checks in this\nchapter's demo (every leaf verifies, a forged leaf\nfails, tampering changes the root) are the minimum.\nThese are correctness checks on the implementation,\nnot a security proof of the scheme.\n\n**Prompt.** 'Explain why collision resistance is\nweaker than preimage resistance for a 256-bit hash.'\n\n*Watch for:* confident but reversed statements. Models\nsometimes assert collisions cost $2^{256}$, missing\nthe birthday factor entirely, or garble which\nproperty protects which use case.\n\n*Verification:* the reader should re-derive the\nbirthday bound independently ($m \\approx 2^{n/2}$)\nand check the model's numbers against it. The\ntruncated-hash simulation in this chapter is a fast\nempirical cross-check.\n\n**Prompt.** 'Is it safe to reuse the same nonce\nacross two ECDSA signatures?'\n\n*Watch for:* any answer that does not immediately say\nthis leaks the private key. Nonce reuse is a\ncatastrophic, well-documented failure, and a model\nthat hedges is a warning about the model.\n\n*Verification:* consult the scheme's specification,\nnot the model, for anything a key depends on. Treat\nLLM cryptography as a tier-two claim requiring a\nprimary source.\n\n## Exercises\n\n1. **Birthday bound by simulation.** Extend the\n   `first_collision()` function to truncation widths\n   of 8, 12, 16, and 20 bits. For each, estimate the\n   mean first-collision count over several hundred\n   replications and plot it against $\\sqrt{\\pi N/2}$\n   on log axes. Confirm the slope corresponds to the\n   $2^{n/2}$ law and report the fitted exponent.\n\n2. **Leading-zeros work.** Verify empirically that\n   the expected number of SHA-256 evaluations to find\n   a digest with $k$ leading zero bits is $2^{k}$.\n   Estimate the mean trial count for $k = 8, 12, 16$\n   and compare to $2^{k}$. Explain how this\n   experiment is the kernel of proof-of-work in\n   @sec-pow.\n\n3. **Avalanche at the byte level.** The chapter tested\n   avalanche in bits. Repeat the analysis counting\n   differing bytes out of 32 instead of bits out of\n   256, derive the distribution differing bytes should\n   follow under the random oracle, and test the fit.\n   (Hint: a byte differs with probability\n   $1 - 2^{-8}$.)\n\n4. **Merkle proof forgery.** Attempt to construct a\n   valid inclusion proof for a record not in the tree,\n   without finding a hash collision. Argue from the\n   `merkle_verify()` logic why this reduces to finding\n   a preimage or collision, and state which resistance\n   property each forgery strategy would have to defeat.\n\n5. **Second-preimage on a truncated hash.** Using\n   truncation to make it feasible, empirically estimate\n   the work to find a second input hashing to the same\n   truncated digest as a fixed target, and confirm it\n   scales as $2^{b}$ rather than $2^{b/2}$. Explain why\n   this differs from the collision experiment in\n   exercise 1.\n\n6. **Group order.** For the toy curve\n   $y^{2} = x^{3} + 2x + 3$ over $\\mathbb{F}_{97}$,\n   enumerate all points (the chapter's `pts` matrix,\n   plus the point at infinity) and count them. Verify\n   that the count equals the group order, and check\n   Lagrange's theorem by confirming that the order of a\n   chosen point divides it.\n\n## Further reading\n\nThe Merkle tree originates with @merkle1988digital,\nwhich introduces the hash tree as a way to sign many\nmessages from one public value; read it for the\nconstruction in its original framing. The\ntimestamping papers of @haber1991timestamp are the\ndirect ancestors of the tamper-evident-log idea and\nmake explicit that chronology and integrity are\nhashing problems, a useful corrective to\nblockchain-first accounts. For public-key\ncryptography, @diffie1976new is the conceptual origin\nand @rivest1978method the first concrete realisation;\nboth are short and worth reading as primary sources.\n\nOn signatures, @schnorr1991efficient introduces the\nscheme whose linearity underlies modern aggregation,\nand @boneh2001short introduces the short pairing-based\nsignatures that make proof-of-stake consensus\ntractable at @sec-pos scale. The zero-knowledge\nframework is @goldwasser1989knowledge, foundational\nfor the privacy constructions later chapters build on.\nFor the primitives in blockchain context,\n@narayanan2016bitcoin (chapters 1 and 4) gives the\nrigorous treatment this chapter matches to a\nstatistical audience, and @antonopoulos2017mastering\ngives the concrete Bitcoin realisations of hashing,\nMerkle trees, and ECDSA. The proof-of-work use of the\nleading-zeros bound traces to @back2002hashcash, which\n@sec-pow develops in full.\n\n## In conclusion\n\nIn conclusion, three points are to be emphasised.\nFirst, the security of every mechanism in this\nchapter is quantitative and conditional, resolved\ninto a specific cost under current cryptanalysis\n(preimage resistance at about $2^{n}$, collision\nresistance at about $2^{n/2}$ by the birthday\nbound), and never the flat 'unbreakable' of\nmarketing copy; an analyst who conflates the two\nresistance properties will overstate by the square\nroot of the security exponent. Second, the\nstatistical tests we ran on the hash validate the\nrandom-oracle model as one validates an assay,\nestablishing that the output is consistent with the\nmodel at the margins we were able to examine while\nestablishing nothing about structure we did not\ntest, and the distinction between failing to reject\nuniformity and proving security is the whole of the\ndiscipline. Third, for the trial ledger the right\nprimitive is the Merkle commitment to the locked\ndataset, which needs no blockchain, and the\nstatistician's contribution lies as much in\ndeclining to reach for consensus machinery that a\nsingle honest publication renders unnecessary as in\ndeploying the cryptography where a genuine trust\nfailure warrants it.\n",
    "supporting": [
      "02-cryptographic-primitives_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}